image: node:15.10.0

stages:
  - build
  - deploy

cache:
  path:
    -node_modules/

build-pages:
  stage: build
  script:
    -rm -rf build
    -CI=false npm install
    -CI=false npm run build
    -rm -rf public
    -cp build/index.html build/404.html
    -mv build public
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - ls
  artifacts:
    paths:
      - public

